# Generated by Django 6.0.7 on 2026-09-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_set_platform_for_existing_warehouses'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tires.platform', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Начальник склада'), ('storekeeper', 'Кладовщик')], default='storekeeper', max_length=20, verbose_name='Роль'),
        ),
    ]
