# Generated by Django 6.0.5 on 2026-06-28 13:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tires', '0002_remove_transferdocumentitem_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('receipt', 'Приемка'), ('movement', 'Перемещение'), ('dispatch', 'Отгрузка'), ('return', 'Возврат')], max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер документа')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('saved', 'Сохранен'), ('posted', 'Проведен')], default='draft', max_length=20, verbose_name='Статус')),
                ('document_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата документа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Пометка на удаление')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создан')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_documents', to='tires.warehouse', verbose_name='Со склада')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_documents', to='tires.warehouse', verbose_name='На склад')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='warehouse.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание'), ('transfer', 'Перемещение')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('movement_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата движения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.document', verbose_name='Документ')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='tires.warehouse', verbose_name='Со склада')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_movements', to='tires.tire', verbose_name='Шина')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='tires.warehouse', verbose_name='На склад')),
            ],
            options={
                'verbose_name': 'История перемещения',
                'verbose_name_plural': 'История перемещений',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номенклатура')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.document', verbose_name='Документ')),
                ('tires', models.ManyToManyField(related_name='document_items', to='tires.tire', verbose_name='Шины')),
            ],
            options={
                'verbose_name': 'Позиция документа',
                'verbose_name_plural': 'Позиции документов',
                'ordering': ['id'],
                'unique_together': {('document', 'product_name')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='warehouse_d_documen_e013e4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'document_date'], name='warehouse_d_status_a2a838_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousemovement',
            index=models.Index(fields=['movement_date'], name='warehouse_w_movemen_70ffeb_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousemovement',
            index=models.Index(fields=['tire'], name='warehouse_w_tire_id_9f582b_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousemovement',
            index=models.Index(fields=['from_warehouse', 'to_warehouse'], name='warehouse_w_from_wa_b70253_idx'),
        ),
    ]
