# Generated by Django 6.0.5 on 2026-06-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Пометка на удаление'),
        ),
    ]
