# Generated by Django 6.0.5 on 2026-06-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE warehouse_document SET status = 'saved' WHERE status = 'draft';",
            reverse_sql="UPDATE warehouse_document SET status = 'draft' WHERE status = 'saved';"
        ),
    ]
