# Generated by Django 6.0.5 on 2026-07-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_update_draft_to_saved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='nomenclature_key',
            field=models.CharField(blank=True, help_text='size+brand+model для группировки', max_length=200, verbose_name='Ключ номенклатуры'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('saved', 'Сохранен'), ('posted', 'Проведен'), ('deleted', 'Удален')], default='saved', max_length=20, verbose_name='Статус'),
        ),
    ]
