# Generated by Django 6.0.7 on 2026-09-21 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0007_migrate_tire_to_tirecode'),
        ('warehouse', '0003_documentitem_nomenclature_key_alter_document_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('writeoff', 'Списание'), ('buyout', 'Выкуп')], max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('prefix', models.CharField(max_length=5, verbose_name='Префикс номера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='warehousemovement',
            name='warehouse_w_movemen_70ffeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousemovement',
            name='warehouse_w_tire_id_9f582b_idx',
        ),
        migrations.RemoveIndex(
            model_name='warehousemovement',
            name='warehouse_w_from_wa_b70253_idx',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='warehouse_d_documen_e013e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='warehouse_d_status_a2a838_idx',
        ),
        migrations.AlterUniqueTogether(
            name='documentitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='document',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='tires.platform', verbose_name='Площадка-источник'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_documents', to='tires.warehouse', verbose_name='Склад-источник'),
        ),
        migrations.AddField(
            model_name='document',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_documents', to='tires.warehouse', verbose_name='Склад-получатель'),
        ),
        migrations.AddField(
            model_name='document',
            name='writeoff_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_documents', to='tires.platform', verbose_name='Площадка списания'),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='nomenclature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_items', to='tires.tirenomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('saved', 'Сохранён'), ('posted', 'Проведён'), ('marked_deleted', 'Помечен на удаление')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='documentitem',
            constraint=models.UniqueConstraint(fields=('document', 'nomenclature'), name='unique_item_per_document_and_nomenclature'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='warehouse.doctype', verbose_name='Тип документа'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['number'], name='warehouse_d_number_6d8e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='warehouse_d_status_ea07de_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_platform', 'status'], name='warehouse_d_source__3c7e80_idx'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='document',
            name='to_warehouse',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='nomenclature_key',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='documentitem',
            name='tires',
        ),
        migrations.DeleteModel(
            name='WarehouseMovement',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
