# Generated by Django 6.0.5 on 2026-06-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferdocumentitem',
            name='document',
        ),
        migrations.RemoveField(
            model_name='transferdocumentitem',
            name='tires',
        ),
        migrations.DeleteModel(
            name='TransferDocument',
        ),
        migrations.DeleteModel(
            name='TransferDocumentItem',
        ),
    ]
