# Generated by Django 6.0.7 on 2026-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_remove_transferdocumentitem_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название площадки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['name'],
            },
        ),
    ]
