# Generated by Django 6.0.7 on 2026-09-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_add_platform_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tires.platform', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название склада'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'Основной склад'), ('oh', 'Ответственное хранение')], default='main', max_length=20, verbose_name='Тип склада'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('name', 'platform'), name='unique_warehouse_per_platform'),
        ),
    ]
