# Generated by Django 6.0.7 on 2026-09-21 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0005_set_platform_for_existing_warehouses'),
        ('warehouse', '0003_documentitem_nomenclature_key_alter_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['brand', 'model', 'size'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'model', 'size'), name='unique_nomenclature')],
            },
        ),
        migrations.CreateModel(
            name='TireCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.CharField(max_length=100, unique=True, verbose_name='QR-код (DataMatrix)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('honest_sign_data', models.JSONField(blank=True, null=True, verbose_name='Данные Честный Знак')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_codes', to='warehouse.document', verbose_name='Документ')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_codes', to='tires.supplier', verbose_name='Поставщик')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tire_codes', to='tires.warehouse', verbose_name='Склад')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tire_codes', to='tires.tirenomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Код шины',
                'verbose_name_plural': 'Коды шин',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'is_active', 'created_at'], name='tirecode_warehouse_active_created_idx')],
            },
        ),
    ]
