# Generated by Django 6.0.7 on 2026-09-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0007_migrate_tire_to_tirecode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tirecode',
            new_name='tirecode_wh_active_idx',
            old_name='tirecode_warehouse_active_created_idx',
        ),
    ]
