# Generated by Django 6.0.5 on 2026-06-18 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('export_format', models.CharField(choices=[('txt', 'Text File'), ('qr_images', 'QR Code Images')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tire_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пакет экспорта',
                'verbose_name_plural': 'Пакеты экспорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/')),
                ('file_type', models.CharField(choices=[('txt', 'Text File'), ('pdf', 'PDF File')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Импорт файла',
                'verbose_name_plural': 'Импорты файлов',
                'ordering': ['-upload_date'],
            },
        ),
    ]
