# Generated by Django 6.0.7 on 2026-09-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimport',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='Детали пропущенных кодов'),
        ),
        migrations.AlterField(
            model_name='fileimport',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='Лог'),
        ),
    ]
